name: projeto_704apps
description: Projeto pessoal

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  http_interceptor: ^2.0.0
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.0+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:

  uses-material-design: true