name: projeto_704apps
description: Projeto pessoal

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  http_interceptor: ^2.0.0
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.0+1
  provider: ^6.1.2
  flutter_sound: ^9.2.13 
  sqflite: ^2.4.2
  workmanager: ^0.6.0 
  path_provider: ^2.1.1 
  permission_handler: ^12.0.0 
  audioplayers: ^6.5.0 
  path: ^1.8.3
  camera: ^0.11.1
  record: ^6.0.0 
  flutter_background_service: ^5.1.0 
  flutter_tts: ^4.2.3
  flutter_overlay_window: 0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/LOGO_ZAFIRA-01.png
    - assets/images/LOGO_ZAFIRA-01b.png
    - assets/images/LOGO_ZAFIRA-02.png
    - assets/images/LOGO_ZAFIRA-03.png
    - assets/images/WhatsApp_Image_2025-06-20_at_17.56.48-removebg-preview.png